version: "2"
run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
linters:
  settings:
    wsl:
      force-err-cuddling: true
      allow-assign-and-call: true
      allow-multiline-assign: true
      allow-cuddle-declarations: false
      allow-trailing-comment: false
      force-case-trailing-whitespace: 0
      strict-append: true
  exclusions:
    rules:
      - linters:
          - staticcheck
        text: "SA5008: unknown JSON option"
